import {
  configureFonts,
  MD3DarkTheme,
  MD3LightTheme,
  MD3Theme,
} from 'react-native-paper';
import { Colors } from './colors';
import { BorderRadius, Fonts } from './typography';

const fontConfig = {
  displayLarge: {
    fontFamily: Fonts.bold,
    fontSize: 40,
    lineHeight: 48,
    fontWeight: '700' as const,
    letterSpacing: -0.5,
  },
  displayMedium: {
    fontFamily: Fonts.bold,
    fontSize: 34,
    lineHeight: 42,
    fontWeight: '700' as const,
    letterSpacing: 0,
  },
  displaySmall: {
    fontFamily: Fonts.bold,
    fontSize: 30,
    lineHeight: 38,
    fontWeight: '700' as const,
    letterSpacing: 0,
  },
  headlineLarge: {
    fontFamily: Fonts.bold,
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '700' as const,
    letterSpacing: 0,
  },
  headlineMedium: {
    fontFamily: Fonts.bold,
    fontSize: 24,
    lineHeight: 32,
    fontWeight: '700' as const,
    letterSpacing: 0,
  },
  headlineSmall: {
    fontFamily: Fonts.semiBold,
    fontSize: 22,
    lineHeight: 28,
    fontWeight: '600' as const,
    letterSpacing: 0,
  },
  titleLarge: {
    fontFamily: Fonts.semiBold,
    fontSize: 20,
    lineHeight: 26,
    fontWeight: '600' as const,
    letterSpacing: 0,
  },
  titleMedium: {
    fontFamily: Fonts.semiBold,
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '600' as const,
    letterSpacing: 0.15,
  },
  titleSmall: {
    fontFamily: Fonts.medium,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '500' as const,
    letterSpacing: 0.1,
  },
  labelLarge: {
    fontFamily: Fonts.semiBold,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600' as const,
    letterSpacing: 0.1,
  },
  labelMedium: {
    fontFamily: Fonts.medium,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '500' as const,
    letterSpacing: 0.3,
  },
  labelSmall: {
    fontFamily: Fonts.medium,
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '500' as const,
    letterSpacing: 0.3,
  },
  bodyLarge: {
    fontFamily: Fonts.regular,
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '400' as const,
    letterSpacing: 0.15,
  },
  bodyMedium: {
    fontFamily: Fonts.regular,
    fontSize: 14,
    lineHeight: 22,
    fontWeight: '400' as const,
    letterSpacing: 0.15,
  },
  bodySmall: {
    fontFamily: Fonts.regular,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '400' as const,
    letterSpacing: 0.2,
  },
};

const sharedTheme = {
  roundness: BorderRadius.lg,
  fonts: configureFonts({ config: fontConfig }),
};

export const LightTheme: MD3Theme = {
  ...MD3LightTheme,
  ...sharedTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: Colors.primary,
    onPrimary: Colors.white,
    primaryContainer: Colors.primaryLight,
    secondary: Colors.secondary,
    secondaryContainer: Colors.secondaryLight,
    tertiary: Colors.success,
    tertiaryContainer: Colors.successLight,
    background: Colors.light.background,
    surface: Colors.light.surface,
    surfaceVariant: Colors.light.surfaceVariant,
    onSurfaceVariant: Colors.light.onSurfaceVariant,
    onBackground: Colors.light.onBackground,
    onSurface: Colors.light.onSurface,
    error: Colors.error,
    outline: Colors.light.outline,
    outlineVariant: Colors.light.divider,
    shadow: Colors.light.shadow,
    backdrop: 'rgba(16, 32, 58, 0.32)',
    elevation: {
      ...MD3LightTheme.colors.elevation,
      level0: Colors.light.background,
      level1: Colors.light.surface,
      level2: Colors.light.surfaceVariant,
      level3: '#F7FAFF',
      level4: Colors.light.card,
      level5: Colors.light.hero,
    },
    surfaceDisabled: '#DDE5F0',
    onSurfaceDisabled: '#7C8698',
  },
};

export const DarkTheme: MD3Theme = {
  ...MD3DarkTheme,
  ...sharedTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary: Colors.primary,
    onPrimary: Colors.white,
    primaryContainer: '#102544',
    onPrimaryContainer: '#E7EFFF',
    secondary: Colors.secondary,
    secondaryContainer: '#3A2419',
    onSecondaryContainer: '#FFE1D3',
    tertiary: Colors.success,
    tertiaryContainer: '#153127',
    onTertiaryContainer: '#D4F7E8',
    background: Colors.dark.background,
    surface: Colors.dark.surface,
    surfaceVariant: Colors.dark.surfaceVariant,
    onSurfaceVariant: Colors.dark.onSurfaceVariant,
    onBackground: Colors.dark.onBackground,
    onSurface: Colors.dark.onSurface,
    error: Colors.error,
    outline: Colors.dark.outline,
    outlineVariant: Colors.dark.divider,
    shadow: Colors.dark.shadow,
    backdrop: 'rgba(3, 8, 16, 0.64)',
    elevation: {
      ...MD3DarkTheme.colors.elevation,
      level0: Colors.dark.background,
      level1: Colors.dark.surface,
      level2: Colors.dark.surfaceVariant,
      level3: Colors.dark.surfaceElevated,
      level4: Colors.dark.card,
      level5: Colors.dark.hero,
    },
    surfaceDisabled: '#243149',
    onSurfaceDisabled: '#7E91AE',
  },
};
